version: '3.0'
volumes:
  signer-volume:
  ipc-volume:
  log-volume:
services:
  signer:
    env_file:
      - signer.env
    build:
      context: ./node_modules/gittoken-signer/.
    ipc: host
    volumes:
      - signer-volume:/keystore/
      - ipc-volume:/tmp/
  webhookmgr:
    ports:
      - 3000:3000
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - signer
    ipc: signer
    volumes:
      - log-volume:/db
      - ipc-volume:/tmp/
